pipeline {
    agent any

    environment {
        // Define environment variables  
        REGISTRY_URL = "account-id.dkr.ecr.eu-central-1.amazonaws.com/coding-test"
        IMAGE_NAME = 'coding-test' // Name of the image
        IMAGE_TAG = 'latest' // tag name
    }

    stages {
        stage('Tag and Push Image') {
            steps {
                script {
                    // Tag the image for the registry
                    sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}"
                    // login ECR repository and push the image
                    sh "aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${REGISTRY_URL}"
                    sh "docker push ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }

    post {
        success {
            echo 'Push to registry succeeded!'
        }
        failure {
            echo 'Push to registry failed!'
        }
    }
}

